- README.md
> Added reference to EPEL in README

- roles/sat6repro/tasks/main.yml
> Update katello assets only for Satellite 6.1 cloning.

- roles/sat6repro/tasks/main.yml
- roles/sat6repro/vars/main.yml
> Introduce custom option to disable firewall for testing purposes.

- roles/sat6repro/tasks/main.yml
- roles/sat6repro/vars/main.yml
> Option to run katello reindex

- .gitignore
- README.md
- roles/sat6repro/tasks/main.yml
- roles/sat6repro/tasks/reset_pulp_data.yml
- roles/sat6repro/tasks/restore.yml
- roles/sat6repro/vars/main.yml
Adding the ability to transfer pulp_data file when cloning a satellite
> Adding pulp data transfer capability

- roles/sat6repro/tasks/main.yml
> Installing libselinux-python package after enabling base os repo

- roles/sat6repro/tasks/main.yml
> fixed identifying free space in root fs

- roles/sat6repro/tasks/main.yml
> Added a sleep before hammer ping so that foreman-task service cleanly comes up

- roles/sat6repro/tasks/main.yml
> Require libselinux-python in rhel6 sooner

- roles/sat6repro/tasks/pre_install_check.yml
> Added validation for the presence of the backup tar files before starting cloning process

- roles/sat6repro/tasks/main.yml
> Remove epel-release package in rhel6

- README.md
- helpers/control_node_setup.sh
> Introducing helper scripts to automate the manual steps

- roles/sat6repro/tasks/main.yml
> Workaround for clone failure for Sat boxes upgraded from 6.1 to 6.2

- docs/cloning.md
> Added warning about the usage of large pulp backup files.

- roles/sat6repro/tasks/main.yml
- roles/sat6repro/vars/main.sample.yml
> Use reimport instead of reindex for 6.2

- roles/sat6repro/tasks/main.yml
- roles/sat6repro/vars/main.sample.yml
> Make RH portal registration optional.

- docs/satellite-clone.md
> Add note about refreshing a manifest

- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/main.yml
- satellite-clone-vars.sample.yml
> Determine satellite version from backup

- roles/satellite-clone/tasks/main.yml
- roles/satellite-clone/tasks/restore.yml
> Turn off verbose output for tar commands

- roles/satellite-clone/tasks/main.yml
> Clarify katello reindex and reimport in task names

- roles/satellite-clone/tasks/restore.yml
Fixes #146
We should ensure this service is started for sat 6.1
> Start psql after stopping for restore

- .gitignore
- ansible.cfg
- docs/faqs.md
> Introduced log file for storing ansible playbook outputs

- roles/satellite-clone/tasks/main.yml
> Remove EPEL before satellite installer runs

- roles/satellite-clone/tasks/restore.yml
> Fix mongo restore regression in migration scenario

- roles/satellite-clone/tasks/backup_check.yml
Fixes #155
We need way of checking that one and only one backup is present.
> Fix backup check

- docs/satellite-clone.md
- helpers/postgresql_dump.sh
- helpers/rhel_6_to_7_migration_backup.sh
> Fix permission issues and refactor postgresql_dump helper script

- roles/satellite-clone/tasks/main.yml
> Remove vim install

- roles/satellite-hostname/tasks/main.yml
> Change hostname log file name incorrect

- roles/satellite-clone/files/disassociate_capsules.rb
> Don't show capsule disassociate message when there are no capsules

- roles/satellite-clone/tasks/main.yml
Fixes #183
I had to do this with satellite 6.2.9 after restoring a backup from an older version.
> Run the installer with --upgrade for all installs

- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/restore_psql_dump.yml
- satellite-clone-vars.sample.yml
> add option to run pg_restore

- roles/satellite-clone/tasks/main.yml
and activation_key and org are set to "changeme"
Fixes #196
> Playbook shouldn't fail when register to portal is false

- roles/satellite-clone/tasks/restore_psql_dump.yml
> adding else to conditionals in restore postgresql cmds

- roles/satellite-clone/tasks/main.yml
> fix conditonal statement

- docs/satellite-clone.md
- roles/satellite-clone/tasks/main.yml
> Disable REX on install

- roles/satellite-clone/tasks/backup_check.yml
Duplicate phrase for online backup.
> duplicate phrase in roles/satellite-clone/tasks/backup_check.yml

- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/main.yml
- satellite-clone-vars.sample.yml
This is useful when fixing permission errors resulting from a bad backup
Fixes #220
> Add option to restorecon the filesystem

- roles/satellite-clone/defaults/main.yml
- satellite-clone-vars.sample.yml
> Change disable postgres triggers to true

- docs/satellite-clone.md
> Updates refresh manifest part of docs

- bin/satellite-clone
> Add --list-tasks

- roles/satellite-clone/tasks/main.yml
> Remove jmx.conf

- docs/satellite-clone.md
- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/pre_install_check.yml
- satellite-clone-vars.sample.yml
> Remove space calculation check

- bin/satellite-clone
> Exit properly on error in production script

- roles/satellite-clone/tasks/backup_check.yml
> Update error msg for online backup

- README.md
- docs/satellite-clone.md
- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/main.yml
- satellite-clone-vars.sample.yml
> Add flexibility to enable required repos

- roles/satellite-clone/tasks/main.yml
> Use cached variables for candlepin and foreman dump check

- docs/satellite-clone.md
> Steps to restore pulp content after cloning.

- bin/satellite-clone
We are calling cli.run() twice and need to remove one
Fixes #320
> Remove unnecessary playbook run

- bin/satellite-clone
> Adds --assume-yes

- roles/satellite-clone/tasks/main.yml
> Remove jmx.conf before first installer run

- roles/satellite-clone/files/disassociate_capsules.rb
> shellescape all strings when disassociating capsules

- roles/satellite-clone/vars/satellite_6.4.yml
> Reset puppet server ssl chain on install

- roles/satellite-clone/tasks/main.yml
> Exclude /var/lib/foreman/public/assets from cloning

- roles/satellite-clone/tasks/main.yml
> Fixed hammer-setup required for foreman-maintain

- docs/satellite-clone.md
- roles/satellite-clone/tasks/main.yml
Seems to work well. I left some comments with questions about areas of the playbook that need some explanation. Opted to not do any other refactoring at this time, but open to feedback on that!
> Fixes #27808 - Use foreman-maintain to restore backup

- docs/satellite-clone.md
- roles/satellite-clone/tasks/main.yml
- roles/satellite-clone/vars/satellite_6.5.yml
- roles/satellite-clone/vars/satellite_6.6.yml
- roles/satellite-clone/vars/satellite_6.7.yml
- roles/satellite-clone/vars/satellite_6.8.yml
> Install DB packages so health checks works in remote db setups

- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/backup_satellite_version_check.yml
- roles/satellite-clone/tasks/interface_check.yml
includes #398, for obvious reasons ;)
> detect answers file path automatically

- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/main.yml
this is the same since we dropped support for 6.5 and older
> remove sp_features_table_name variable

- roles/satellite-clone/tasks/main.yml
> also do firewall actions on non-el7

- README.md
> document 6.10 support

- roles/satellite-clone/defaults/main.yml
- roles/satellite-clone/tasks/main.yml
- roles/satellite-clone/tasks/reset_pulpcore_data.yml
- satellite-clone-vars.sample.yml
> reset pulpcore data for Satellite 6.10+
