RedHatSatellite/satellite-clone

roles/sat6repro/tasks/main.yml

The colon in task name caused parsing issues in ansible run.

Removed exclamation from ansible task name

---

README.md

HTTPS is better for anon access, since you don't need to setup keys.

Changed URL in 'git clone' to HTTPS.

---

README.md
roles/sat6repro/tasks/main.yml

Reasons:
1. The tasks mentioned in the sat6repro/tasks/main.yml should be focusing only on updating the Satellite host
2. Installing of a task requires that Ansible needs to run as a root user on the Control node which is not a recommended practice.
Fixes #37

Remove rsync install task on the Ansible Control node.

---

roles/sat6repro/tasks/main.yml
roles/sat6repro/tasks/pre_install_check.yml
roles/sat6repro/vars/main.sample.yml

1. Replace df with ansible facts to calculate the free space of the host
2. Introducing a new task file to hold the pre-install checks
3. Giving an option to the user to disable pre-install checks if required

Improvements to free space calculation.

---

docs/cloning.md
roles/sat6repro/tasks/main.yml
roles/sat6repro/tasks/restore.yml
roles/sat6repro/vars/main.sample.yml

Why?
The copy or synchronize Ansible modules are unreliable while transfering large files and we see errors often in these scenarios.  Alternatively, the user has to push the backup files on the Destination node manually.
Fixes #60

Removed copy/synchronize tasks from the satellite-clone tool.

---

roles/sat6repro/tasks/main.yml

tested up to this step to make sure it worked
```
TASK [sat6repro : register host] ***********************************************
changed: [192.168.121.78]
TASK [sat6repro : disable all repos] *******************************************
changed: [192.168.121.78]
TASK [sat6repro : Enable required repos] ***************************************
changed: [192.168.121.78]
TASK [sat6repro : install libselinux-python for rhel6] *************************
dchanged: [192.168.121.78]
TASK [sat6repro : turn off firewalld - rhel7] **********************************
skipping: [192.168.121.78]
TASK [sat6repro : turn off firewall - rhel6] ***********************************
skipping: [192.168.121.78] => (item=service iptables stop) 
skipping: [192.168.121.78] => (item=chkconfig iptables off) 
TASK …
```

Reorder steps to avoid libselinux-python errors

---

README.md

I was going through the documentation and found that link seems to be broken to setup control node. I've updated the link for the script. Thanks

Update README.md for control_node_setup script link

---

roles/sat6repro/tasks/main.yml
roles/sat6repro/tasks/pre_install_check.yml
roles/sat6repro/vars/main.sample.yml

The satellite-clone playbook was also used to quickly install a sat 6.1 or sat 6.2 box without actually restoring backup data. But this beats the purpose of this playbook and this playbook should stay simple and support just cloning. So perform_restore option will be removed.  A new playbook needs to be created in future if there is an intent to support plain install of Satellite without backup data.
Fixes #97

Remove `perform_restore` option from configs.

---

docs/cloning.md
roles/sat6repro/tasks/main.yml
roles/sat6repro/vars/main.sample.yml

- This makes the config even easier since the user doesn't need to fetch this manually.
Fixes #21

Derive the hostname from the backup config files.

---

roles/sat6repro/tasks/restore.yml

- This is not really needed in pulp as this is part of inter satellite sync
Fixes #81

Skipping untaring /var/lib/pulp/katello-export

---

roles/satellite-clone/tasks/main.yml

Updated the confusing task name for libselinux-python package install.

Improve the task name for libselinux-python package install

---

roles/satellite-clone/tasks/restore.yml

Fix: force stopping postgresql
I am enabling this task for both 6.1 and 6.2 to make sure that postgresql is indeed stopped while restoring postgresql data.

Satellite 6.1 doesn't stop postgresql while stopping katello-service

---

docs/satellite-clone.md
roles/satellite-clone/files/disassociate_capsules.rb
roles/satellite-clone/tasks/main.yml

Fixes #134
The cloned satellite will still try to communicate with existing capsules,
so we can disassociate them to avoid any connection issues and interference
with exisiting setup. When the user has configured the capsules properly,
there will be instructions on how to reassociate the capsules.

Disassociate capsules with lifecycle environments

---

roles/satellite-hostname/tasks/main.yml

Our default password is "changeme" in dev environments and after a clone, so this check fails quite a bit. Just checking the new_hostname and admin_username have changes is enough to tell if the user has edited the file.
We should probably refine this check a bit more, but this will unblock automation for now

don't check password is changeme on hostname change

---

packaging/satellite-clone.rb

This is a wrapper script that will allow us to
use a cli tool when this repo is packaged. It
works off of the yml config files that ansible
uses in order to not duplicate the parameters
and documentation we have in those files

adds wrapper script

---

roles/satellite-clone/tasks/main.yml

Fixes #162
In order to restore the backup without error, we have to
ensure the permissions are correct on the backup

[WIP] - Correct permissions in backup

---

roles/satellite-clone/tasks/main.yml

If the user is disabling "register to portal", it means they have
already enabled the necessary repos and we shouldn't do anything
with subscriptions.

Don't enable or disable repos when register to portal is false.

---

roles/satellite-clone/tasks/main.yml

After the installer runs, if there is an error, we want to disassociate capsules from lifecycle environments.
This is to prevent the clone trying to sync with existing original capsules. We do this with SQL in case
hammer is not able to execute a command.

Disassociate capsules on playbook error

---

README.md

Hi,
Currently the ansible package is not available from EPEL so rather use rhel-7-server-extras-rpms repository.
[root@~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
This system is registered with an entitlement server, but is not receiving updates. You can use subscription-manager to assign subscriptions.
repo id                                                                              repo name                                                                                                               status
epel/x86_64                                                                          Extra Packages for Enterprise Linux 7 - x86_64                                                                          12,005
repolist: 12,005
Loaded …

Ansible is not available in EPEL, changed it to RHEL7 extras repo

---

roles/satellite-clone/tasks/main.yml

Fixes #250
The pause module displays a prompt:
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
This could break out of the executable script in production installs.
We should use an alternative command/module that doesn't display this prompt

Don't use pause module

---

roles/satellite-clone/tasks/reset_pulp_data.yml

Fixes #255
When cloning w/o pulp_data.tar, the database has to be migrated
to recreate indexes and prevent errors like duplicate key errors.

Fixes pulp duplicate key error

---

roles/satellite-clone/tasks/main.yml

Paused tasks can block the upgrade step after the restore.
Fixes #252

Cleanup paused tasks

---

roles/satellite-clone/tasks/main.yml

Fixes #261 - The candlepin database can be restored from an
earlier sat version, so we can migrate it before running the upgrade
to avoid issues.

Migrate cp database after install

---

docs/satellite-clone.md
roles/satellite-clone/tasks/main.yml

This reverts commit 09387bf5bb39dc179c854364f984c41192d307c7.
Fixes #272 - see issue for more context

Revert "Disable REX on install"

---

roles/satellite-clone/tasks/main.yml

This allows activation keys like 'Satellite 6.3 RHEL7'

Allow multi-word activation key names

---

roles/satellite-clone/tasks/reset_pulp_data.yml
roles/satellite-clone/tasks/restore_mongo_dump.yml

The echo command we were using wasn't actually dropping the mongo
database, but rather echoing 'db.dropDatabase();' | mongo pulp_database
This resulted in data being restored on an existing database.
So the mongo database stayed during restore. We didn't notice many issues
because not much is in the mongo database on a clean satellite install.
Fixes #259

Actually drop mongodb

---

roles/satellite-clone/defaults/main.yml
roles/satellite-clone/tasks/main.yml
satellite-clone-vars.sample.yml

Some users have custom /etc/hosts files
to resolve to the cdn or similar, they can
use this option to custom configure their
/etc/hosts before running the clone.
Fixes #281

Add option to not overwrite /etc/hosts

---

roles/satellite-clone/defaults/main.yml
roles/satellite-clone/tasks/main.yml
satellite-clone-vars.sample.yml

By default,
- the server will not be registered to Red Hat Portal
- It is the responsibility of the user to provide right repos for
satellite installation.
Override this setting to `yes` and update `activationkey` and `org`
variables to do the portal regisration automatically.
Fixes #285

Made portal registration disabled by default.

---

ansible.production.cfg

Don't create retry files in production

---

ansible.cfg

- Ansible retry option is mainly for running the tasks on multiple
machines.  This is not currently applicable for satellite-clone.

Disabled Ansible retry option.

---

roles/satellite-clone/tasks/main.yml

- libselinux package check was primarily written for rhel6 which is not
supported in targer server anymore.
Fixes #312

Removal of libselinux package check

---

README.md
docs/satellite-clone.md
library/check_metadata_for_satellite_version.py
roles/satellite-clone/files/disassociate_capsules.rb
roles/satellite-clone/tasks/backup_check.yml
roles/satellite-clone/tasks/backup_satellite_version_check.yml
roles/satellite-clone/tasks/main.yml
roles/satellite-clone/tasks/reset_pulp_data.yml
roles/satellite-clone/tasks/restore.yml

This adds an ansible module to check the metadata file in the backup
for a specific version. Because metadata.yml was added in 6.2.z,
the previous check of satellite-answers is kept for older 6.2 backups.
Any backup with metadata.yml will use the metadata file as a check.
Todo:

Add 6.3 support

---

roles/satellite-clone/tasks/main.yml
roles/satellite-clone/vars/satellite_6.1.yml
roles/satellite-clone/vars/satellite_6.2.yml
roles/satellite-clone/vars/satellite_6.3.yml

Used this today to clone a 6.2 instance and test a 6.3 upgrade, it worked really well. Just had some issues due to:
-  the backup didn't include the custom certs I'm using
- easy enough to copy them over manually.
- this role trying chown postgres <backup dir>, which was on a read-only NFS mount.
- worked around it by chown'ing it on the NFS server.
Anyway made some small code improvements. Thanks!

cleanup Satellite version differences

---

roles/satellite-clone/files/disassociate_capsules.rb

fixes errors like
```
TASK [satellite-clone : Disassociate capsules with lifecycle environments (to avoid the cloned Satellite server talking with live capsules)] ***
...
stdout: Could not remove the lifecycle environment from the capsule:
Error: too many arguments
See: 'hammer capsule content remove-lifecycle-environment --help'
...
All Capsules are unassociated with any lifecycle environments. This is to avoid ...
hammer ... --csv capsule content add-lifecycle-environment --id 25 --environment Env Dev --organization "Org"
```

Fixes #342 - Quote lifecycle environment name

---

.gitignore
README.md
library/parse_backup_metadata.py
roles/satellite-clone/tasks/main.yml
roles/satellite-clone/tasks/reset_pulp_data.yml
roles/satellite-clone/tasks/restore_mongo_dump.yml
roles/satellite-clone/vars/satellite_6.4.yml

I was able to clone my satellite including pulp data with this patch!
There are a few places in the main.yml which references version 6.2, 6.3 but I didn't add 6.4 there arbitrarily. Things seem to be OK but would like some specific feedback on those omissions.

Support for cloning 6.4 Satellite

---

library/parse_backup_metadata.py
roles/satellite-clone/tasks/main.yml
roles/satellite-clone/tasks/reset_pulp_data.yml
roles/satellite-clone/vars/satellite_6.5.yml

- related to #351 
- satellite_6.5.yml is just a copy of the 6.4 version
- I was able to do a successful clone using this patch

cloning sat 6.5

---

roles/satellite-clone/files/disassociate_capsules.rb

The previous code would grab the last listed org for the capsule
and then attempt to lookup all associated lifecycle environments
by that organization.  The result is that if a capsule is associated
with 5 orgs, but only associated with the Library of one or two of them,
it may randomally decide to try to remove the lifecycle env from another org
Closes: #363

Properly dissassociate capsule lifecycle environments

---

README.md
library/parse_backup_metadata.py
roles/satellite-clone/tasks/main.yml
roles/satellite-clone/tasks/reset_pulp_data.yml
roles/satellite-clone/vars/satellite_6.6.yml

I tested this as fully working to clone a Sat 6.6 from the latest build.
Since the repos aren't available publicly you'll need to make this change to tasks/main.yaml - note the OHSNAP hostname you'll need to provide:
```
- name: Enable required repos for Satellite installation
-  command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-server-rpms --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms --enable rhel-{{ ansible_distribution_major_version 
+  #command: subscription-manager repos --enable rhel-{{ ansible_distribution_major_version }}-server-rpms --enable rhel-server-rhscl-{{ ansible_distribution_major_version }}-rpms --enable rhel-{{ ansible_distribution_major_version
+  command: subscription-manager repos --enable rhel-{{ …
```

Support cloning Satellite 6.6

---

roles/satellite-clone/files/disassociate_capsules.rb
roles/satellite-clone/tasks/main.yml

This disables the hammer-cli-csv module by removing it's configuration file from the hammer config. This is an issue on some 6.6 installations, where the file is still present.
A fix could still be needed in the installer, but this commit will fix things for any current backups by ensuring the file is removed.
This also updates the disassociate_capsules script to exclude warnings for all hammer commands where we are parsing the output. It also DRYs up our parsing into one function to make updating this area easier.
You can test just the "disassociate_capsules" script on a Satellite that includes capsules associated with a lifecycle environment. The script will disassociate them and give instructions for reversal.

Disables hammer-cli-csv module and ignore warnings in hammer commands

---

library/get_value_from_yaml_in_tarball.py
roles/satellite-clone/defaults/main.yml
roles/satellite-clone/tasks/main.yml

For Satellite answers and other configs, it helps if we have a way to parse the yaml config files inside the tarball. This commit adds that custom module and updates a place where we parse the configs from the shell.

Add custom module to parse YAML in config file

---

roles/satellite-clone/files/disassociate_capsules.rb
roles/satellite-clone/tasks/main.yml

Before on 6.5 below:
```bash
TASK [satellite-clone : Disassociate capsules with lifecycle environments (to avoid the cloned Satellite server talking with live capsules)] **********************************************************************
Friday 15 May 2020  12:35:40 -0400 (0:00:00.234)       1:07:09.580 ************ 
changed: [localhost]
stdout: All Capsules are unassociated with any lifecycle environments. This is to avoid any syncing errors with your original Satellite and any interference with existing infrastructure. To reverse these changes, run the following commands, making sure to replace the credentials with your own.
hammer -u admin -p changeme --csv capsule content add-lifecycle-environment --id 2 --environment-id 2
stderr: Warning: Option --environment-id is deprecated. Use …
```

Fixes #29871 - Fix Hammer deprecation warning with lce

---

roles/satellite-clone/defaults/main.yml
roles/satellite-clone/tasks/main.yml
roles/satellite-clone/vars/satellite_6.8.yml

They were dropped as dependicnes of the satellite package which now causes the untar operation to fail.
Worked fine on my test box, will kick off dolly on the pr and post the results.

On 6.8+ install selinux packages

---

library/parse_backup_metadata.py
roles/satellite-clone/defaults/main.yml
roles/satellite-clone/tasks/backup_satellite_version_check.yml
roles/satellite-clone/tasks/main.yml

Puppetserver 4 was only present on Satellite 6.3. At present, the oldest
supported Satellite release is Satellite 6.5. So code related to
Puppetserver 4 should be removed.

Remove code related to Puppet version 4

---

roles/satellite-clone/tasks/main.yml
roles/satellite-clone/vars/satellite_6.5.yml
roles/satellite-clone/vars/satellite_6.6.yml
roles/satellite-clone/vars/satellite_6.7.yml
roles/satellite-clone/vars/satellite_6.8.yml
roles/satellite-clone/vars/satellite_6.9.yml

In d42eca22bff6818f36a888e986b76313e8cef7b9 support for Satellite 6.1 was dropped. This was the last version that needed the capsule module. Since 6.2 it's always the same.

Remove capsule_puppet_module variable

---

roles/satellite-clone/tasks/backup_satellite_version_check.yml

we don't support any satellite version (pre 6.2) where this file was missing
this was removed in d42eca22bff6818f36a888e986b76313e8cef7b9

don't check for the satellite answers file

---

roles/satellite-clone/tasks/main.yml

let's pretend people who manage their repos know what they are doing

only change EPEL if we're managing repos via `enable_repos`

---

roles/satellite-clone/tasks/main.yml

this was an oversight when cleaning up code and is not needed
Fixes: 56ffd3f1d3e4d377a8986389adab8352ec011773

don't call dnf repolist

---

roles/satellite-clone/tasks/ensure_pulp_data_permissions.yml
roles/satellite-clone/tasks/main.yml

in the case users utilize rsync instead of a backup with pulp data, they
might end up with /var/lib/pulp not being owned by pulp, let's fix that!

ensure pulp user exists and owns /var/lib/pulp for 6.10+

---

roles/satellite-clone/defaults/main.yml
roles/satellite-clone/tasks/main.yml
roles/satellite-clone/vars/satellite_6.6.yml
roles/satellite-clone/vars/satellite_6.7.yml
roles/satellite-clone/vars/satellite_6.8.yml
roles/satellite-clone/vars/satellite_6.9.yml
satellite-clone-vars.sample.yml

`foreman-rake katello:reindex` was previously replaced with
`foreman-rake katello:reimport`. Currently supported versions use
reimport only, so variables tracking which command must be used are dropped.
The variable previously named `run_katello_reindex` is also renamed to
be accurate to the currently supported Satellite versions.

Always use katello:reimport rake, never katello:reindex

---

roles/satellite-clone/tasks/ensure_pulp_data_permissions.yml

Sometimes, if you rsync `/var/lib/pulp` from a different machine, it ends
up being owned by a UID/GID that has no mapping on the new system.
Ansible's `stat` module then doesn't populate the `pw_name` and `gr_name`
attributes, leading to errors like this:
error while evaluating conditional (pulp_stat.stat.pw_name != 'pulp' or pulp_stat.stat.gr_name != 'pulp'): 'dict object' has no attribute 'pw_name'
Catch those cases and still properly fix the permissions.

BZ#2102825 - detect when /var/lib/pulp is owned by an unknown user

---

README.md
library/parse_backup_metadata.py
roles/satellite-clone/vars/satellite_6.12.yml

I have added 6.12 to SUPPORTED_VERSIONS so satellite-clone can work on SAT6.12.
For more info see: https://bugzilla.redhat.com/show_bug.cgi?id=2120992

Added 6.12 version

---

roles/satellite-clone/vars/satellite_6.10.yml
roles/satellite-clone/vars/satellite_6.11.yml
roles/satellite-clone/vars/satellite_6.12.yml

support for changing this was dropped in
b8908342d3797b37218d317e20de24d1d92c84b7, but those files were forgotten
Fixes: b8908342d3797b37218d317e20de24d1d92c84b7

drop verify_rake_task definition from vars files

---

.ansible-lint

requires a release of ansible-lint with https://github.com/ansible/ansible-lint/pull/2732

enable only-builtns ansible-lint rule

---

ansible.cfg
ansible.production.cfg

it's not available in ansible-core and noone complained for it being missing since we moved to EL8

do not enable the profile_tasks callback

---

roles/satellite-clone/library/parse_backup_metadata.py
roles/satellite-clone/tasks/backup_satellite_version_check.yml
roles/satellite-clone/tasks/main.yml

no need to parse URLs
this exists since https://github.com/theforeman/foreman_maintain/commit/bb692bd7f3859ad7834c3c71f1c2c8b989b14c9a which is safe to assume to be present in every backup out there

use hostname from metadata

---

roles/satellite-clone/tasks/main.yml

foreman-maintain runs the installer after the restore for us, no need to repeat things
saves about a minute in my tests :)

don't run installer again after we restored the backup

---

roles/satellite-clone/tasks/backup_check.yml
roles/satellite-clone/tasks/backup_satellite_version_check.yml

https://github.com/ansible/ansible/commit/d955fb1590efaaf996d7a48746e15f71cc65f583 removed the use of this parameter. Anything on RHEL8.10 will have an updated version of ansible, so this currently causes satellite-clone to fail on 8.10.

Remove use of get_md5 parameter in stat module

---

roles/satellite-clone/tasks/main.yml

foreman-maintain takes care of all that, no need to duplicate work

don't stop/start crond and don't start services after restore

---

roles/satellite-clone/tasks/main.yml

this IMHO never made actual sense, but these days all backups are "online" in terms of "have DB dumps"

don't restrict pulp data things to "not online"

---

roles/satellite-clone/tasks/main.yml

fapolicyd doesn't like when we try to execute Python as `postgres`

use runuser instead of become to check postgres perms
